# -*- coding: utf-8 -*-
"""Seaborn library in Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_aBvt-0AGQSfBXm5VHYd4eksN0z7mys
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/USA_Housing.csv")

df.head(10)

df.info()

df.describe()

df.columns

sns.pairplot(df)

sns.heatmap(df.corr(),annot=True)