# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d8F_TBClLNKHoC24hApgZft4-sEXsQ_i
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset from uploaded file
df = pd.read_csv("/content/Tips Dataset.csv")

df.head(10)
df.info()
df.describe()
df.columns

sns.pairplot(df)
sns.heatmap(df.corr(), annot=True)